### PR TITLE
Update dependencies and allow symfony/console v5

### PR DESCRIPTION
**Pull request by red-led**

### CODE REVIEW

**Comment by seyfer** [comment]
@red-led hey, thank you for the contribution.

could you please have a look at why tests are failing?
```
Failure (9 tests, 34/34 methods, 0 void method, 0 skipped method, 0 uncompleted method, 0 failure, 34 errors, 0 exception)!

```

**Comment by red-led** [comment]
@seyfer, looks like errors are related to xdebug config:
> ==> Error E_WARNING in /home/travis/build/Ph3nol/NotificationPusher/vendor/atoum/atoum/classes/test.php on line 1355, generated by file /home/travis/build/Ph3nol/NotificationPusher/vendor/atoum/atoum/classes/test.php on line 1355:
Code coverage needs to be enabled in php.ini by setting 'xdebug.mode' to 'coverage'

`xdebug.mode=coverage` is [new](https://xdebug.org/docs/all_settings#mode) for xdebug3. I have no idea, how to change it in travis builds :(

**Comment by seyfer** [comment]
@red-led thank you, I will have a look this weekend!

**Comment by seyfer** [comment]
@red-led please add this code
```
env:
    global:
        - XDEBUG_MODE=coverage
```

in `.travis.yml` after `php` section. Should work after. :)

**Comment by seyfer** [comment]
@red-led now you have problem with composer install.

Could you please try to update the only composer.json but revert composer.lock changes? It is wrong, I know, but might fix the build.

**Comment by red-led** [comment]
@seyfer done. 

Have you considered not storing `composer.lock` in git at all?

**Review by seyfer — COMMENTED** [review]
all good, thanks!

**Comment by red-led** [comment]
@seyfer, will you publish new release with this changes?

**Comment by goraxan** [comment]
@seyfer I also need the new release with this change, please :)

**Pull request merged**
