### PR TITLE
Add safari push support

### PR DESCRIPTION
**Pull request by alalonde**
Update composer.json

Added support for url-args

Fixed test date warnings

Reverted composer

### CODE REVIEW

**Comment by alalonde** [comment]
Note that this relies on the changes in this other PR: https://github.com/zendframework/ZendService_Apple_Apns/pull/39

**Comment by alalonde** [comment]
The above PR has been merged, so this should be good to go.

**Comment by tscheepers** [comment]
+1

**Comment by seyfer** [comment]
@alalonde, it seems like good PR, thanks! Will merge soon.

**Pull request merged**
