### PR TITLE
FCM Adapter

### PR DESCRIPTION
**Pull request by turbo124**
I've implemented the FCM Adapter for this great library.

I can't take any real credit, essentially I have simply merged the classes derived from the following project

https://github.com/jenky/laravel-push-notification 

Which is built on top of this library anyway.

### CODE REVIEW

**Comment by marktopper** [comment]
Does this handle sending multiple push messages at once? Cause my current build in of this can only handling one at the time, ending my push queue to take about a second for each FCM message it have to send. Thats why I have not created my own pull request.

**Comment by turbo124** [comment]
@marktopper I haven't tested it with multiple messages yet. But I would say that if the GCM adapter can handle multiple messages, then this one should also.

**Comment by kernio** [comment]
Actually, there official ZF update to support FCM (in master). 
So you can avoid create new FCM client inside library. 
Just try to update composer to use latest ZF lib.
https://packagist.org/packages/zendframework/zendservice-google-gcm

ping me if you need help.

**Comment by jaystepin** [comment]
Agree with @kernio No need for separate FCM client.

**Comment by DaanGeurts** [comment]
When sending an FCM notification, you can send a notification message with title and body to display so we need more then switching to the new zendservice-google-gcm package alone.
We need some adapter to set the notification property on the payload object

**Comment by seyfer** [comment]
@turbo124, could you please check @kernio idea mentioned above about using official Zend FPM implementation?

**Comment by turbo124** [comment]
@seyfer correct, simply updating to the latest zendservice-google-gcm will implement FCM natively. My original PR was a stop gap waiting for official support and updates to this repo. This PR can be closed out.

**Pull request closed without merging**
