### PR TITLE
Relax version constraints to work with Laravel 5

### PR DESCRIPTION
**Pull request by theduke**

### CODE REVIEW

**Comment by seyfer** [comment]
@theduke have you tested it with symfony 4 packages?

**Comment by theduke** [comment]
@seyfer everything seems to be working fine with Laravel 5.6 in my manual testing.

How extensive is the test suite?
Because the 7.1 and 7.2 tests will use the latest packages with the 4.x versions too.

**Comment by seyfer** [comment]
@theduke you can see in https://github.com/Ph3nol/NotificationPusher/blob/master/.travis.yml
that it runs on 7.1 and 7.2 also. Shall work. :) will tag new version soon with this PR.

**Comment by seyfer** [comment]
btw. realistically this library build pass only with this deps for Symfony - `>=2.3,<=3.4`

**Pull request merged**
